version: 2
jobs:
  build:
    working_directory: ~/cruxdeploy
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.536

    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: cruxdeploy-{{ checksum "deps.edn" }}
      - run: clojure -R:test -Spath
      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: cruxdeploy-{{ checksum "deps.edn" }}
      - run: clojure -A:run-tests
